version: 2
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
    - checkout
    - run: npm install
    - run: npm run build
    - run: npm run test
    - run: npm run coverage
    - run: npm run make-badges
workflows:
build:
  jobs:
    test